### ISSUE TITLE
Some issues with installation

### ISSUE THREAD

**Issue by RobertNewton-Nomura** [qlitre/django-nuxt3-blog-frontend#2]
Hi! 

Love the blog - thought I'd try get it running as well and then toy around with it,

I'm having some trouble with installing it though, even with following your tutorial at https://qlitre-weblog.com/django-nuxt3-blog/

The backend seems to be working fine; I can add posts etc in the Django admin panel, but when I try to go to the frontend I get the following errors:

私の日本語を許してください、私は翻訳者を使っています

やあ！

ブログが大好きです-私もそれを実行してみて、それからそれをいじってみようと思いました、

https://qlitre-weblog.com/django-nuxt3-blog/のチュートリアルに従っても、インストールに問題があります。

バックエンドは正常に機能しているようです。 Django管理パネルで投稿などを追加できますが、フロントエンドに移動しようとすると、次のエラーが発生します。

http://localhost:3001/
![bug 2](https://user-images.githubusercontent.com/31044075/173187985-00a1147e-c1b4-4aef-babd-0e8a767ddcc6.png)

[nuxt] [request error] Cannot read properties of null (reading 'total_pages')     
  at /D:/coding%20stuff/Nuxt%20Django%20Blog%20Template/django-nuxt3-blog-frontend/.nuxt/dist/server/server.mjs:5032:38
  at renderFnWithContext (D:\coding stuff\Nuxt Django Blog Template\django-nuxt3-blog-frontend\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:846:21)      
  at normalizeChildren (D:\coding stuff\Nuxt Django Blog Template\django-nuxt3-blog-frontend\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:6378:42)       
  at createBaseVNode (D:\coding stuff\Nuxt Django Blog Template\django-nuxt3-blog-frontend\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:6140:9)
  at _createVNode (D:\coding stuff\Nuxt Django Blog Template\django-nuxt3-blog-frontend\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:6233:12)
  at Module.createVNodeWithArgsTransform (D:\coding stuff\Nuxt Django Blog Template\django-nuxt3-blog-frontend\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:6098:12)
  at Proxy.<anonymous> (/D:/coding%20stuff/Nuxt%20Django%20Blog%20Template/django-nuxt3-blog-frontend/.nuxt/dist/server/server.mjs:30271:40)
  at renderComponentRoot (D:\coding stuff\Nuxt Django Blog Template\django-nuxt3-blog-frontend\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:889:44)      
  at renderComponentSubTree (D:\coding stuff\Nuxt Django Blog Template\django-nuxt3-blog-frontend\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:275:51)
  at renderComponentVNode (D:\coding stuff\Nuxt Django Blog Template\django-nuxt3-blog-frontend\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:214:16)

http://localhost:3001/api/blog/post
![django nuxt bug](https://user-images.githubusercontent.com/31044075/173187935-1a68740d-b5cd-4ea0-a583-dcaeff05de46.png)

[Vue Router warn]: No match found for location with path "/api/blog/post"
[Vue Router warn]: No match found for location with path "/api/blog/post"
[Vue Router warn]: No match found for location with path "/api/blog/post"
[Vue Router warn]: No match found for location with path "/api/blog/post"

Do you have any suggestions on potential fixes, or something I could research in order to figure out the issue?

Thanks in advance,
Rob

潜在的な修正について何か提案がありますか、または問題を理解するために私が調査できることはありますか？

前もって感謝します、
ロブ

**Comment by qlitre** [comment]
Thank you for reading my blog.
At first glance, I feel that API authentication is not working.
Is the API key issued on the backend side and described in the .env file on the frontend side?

```
python manage.py shell
>>> from rest_framework_api_key.models import APIKey
>>> api_key, key = APIKey.objects.create_key(name="api-key-dev")
>>> key
'your api key'
>>> exit()
```

frontend/.env
```
BASE_URL=http://127.0.0.1:8000
API_KEY=your api key
```

Thanks,
Qlitre

**Comment by RobertNewton-Nomura** [comment]
All sorted, remade the api key and restarted the servers, thanks!
